apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: tuni-app
data:
  DEBUG: "False"
  DJANGO_SETTINGS_MODULE: "backend.settings"
  ALLOWED_HOSTS: "app.local,localhost"
  CORS_ALLOWED_ORIGINS: "http://app.local,http://localhost:8080"
  CSRF_TRUSTED_ORIGINS: "http://app.local,http://localhost:8080"
