apiVersion: v1
kind: Secret
metadata:
  name: tuni-secrets
  namespace: tuni-app
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "My-Secret"
  DB_NAME: "tuni_db"
  DB_USER: "admin"
  DB_PASSWORD: "admin"
  POSTGRES_DB: "tuni_db"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""
