apiVersion: v1
kind: Secret
metadata:
  name: tuni-secrets
  namespace: tuni-app
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "replace-me"
  DB_NAME: "tuni_db"
  DB_USER: "tuni_user"
  DB_PASSWORD: "tuni_pass"
  POSTGRES_DB: "tuni_db"
  POSTGRES_USER: "tuni_user"
  POSTGRES_PASSWORD: "tuni_pass"
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""
